name: Deploy Application
on:
  workflow_call:
    inputs:
      aws_region:
        required: true
        type: string
      AWS_ACCESS_KEY_ID:
        required: true
        type: string
      AWS_SECRET_ACCESS_KEY:
        required: true
        type: string        

runs:
  using: "composite"
  steps:
      # Setup the AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws_region }}

      #  working-directory: backend/build
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - name: Install Python Dependencies
        run: |
          pip install boto3 
        shell: bash

      - name: Update Crud Lambda
        run: |
          zip -j crudLambda.zip terraform/backend/* #--> Zip the Code As we know lambda function accept the zip file.
          aws lambda update-function-code --function-name=backend_crud_lambda --zip-file=fileb://crudLambda.zip 
        shell: bash  

      - name: Update Canary Lambda
        run: |
          zip -j canaryLambda.zip terraform/canaryLambda/* #--> Zip the Code As we know lambda function accept the zip file.
          aws lambda update-function-code --function-name=backend_canary_lambda --zip-file=fileb://canaryLambda.zip 
        shell: bash        
  