name: Deploy Application Workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Clone the repo
      - name: Clone repository
        uses: actions/checkout@v3

      # Cache node modules
      - name: Cache node modules
        uses: actions/cache@v3  
        with:
          path: ./terraform/backend/node_modules
          key: npm-deps-${{ hashFiles('package-lock') }}
          restore-keys: |
            npm-deps-${{ hashFiles('packagelock') }}

      - name: Install Backed App dependencies
        run: npm install 
        working-directory: ./terraform/backend     

      # Test the Backend app
      - name: Test static build
        run: npm test 
        working-directory: ./terraform/backend    

  should_deploy_backend:
    runs-on: ubuntu-latest
    needs: build
    environment:
       name: dissertation-backend
    steps:
      - name: Should deploy backend?
        run: echo "Should deploy backend?"

  call_deployment_workflow:
    runs-on: ubuntu-latest
    needs: should_deploy_backend
    strategy:
      max-parallel: 1
      matrix:
        aws_region: ["us-east-1","us-east-2","us-west-1"]
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Output Current Directory
        run: pwd && ls -latr
 
      - name: Deploy the application workflow
        uses: ./.github/workflows/deploy_application_workflow
        with:
          aws_region: ${{ matrix.aws_region }}
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    