name: Destroy Application Workflow
on: [push]
jobs:

  should_destroy_backend:
    runs-on: ubuntu-latest
    environment:
      name: dissertation-backend
    steps:
      - name: Should destroy backend?
        run: echo "Should destroy backend?"

  call_destroy_application_workflow:
    runs-on: ubuntu-latest
    needs: should_destroy_backend
    strategy:
      max-parallel: 1
      matrix:
        aws_region: ["us-east-1", "eu-west-1"]
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Output Current Directory
        run: pwd && ls -latr

      - name: Destroy the application workflow
        uses: ./.github/workflows/destroy_application_workflow
        with:
          aws_region: ${{ matrix.aws_region }}
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }} 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    